name: Deploy to Render

on:
  push:
    paths:
      - 'server/**'  # Triggers workflow when anything inside the server folder changes
    branches: 
      - dynamicImages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deployment
        run: |
          curl "$RENDER_DEPLOY_HOOK_URL"
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
